#!/usr/bin/env bash
# =====================================================================
# run_lifton.sh — LiftOn branch (hybrid homology), manual wrapper
#
# Encapsulates the exact commands documented in REPRODUCIBILITY.md (section 3).
# LiftOn is NOT wired into the Snakefile: it was added after the workflow and
# reuses the Liftoff and miniprot annotations already produced by the pipeline.
#
# Prerequisites (see REPRODUCIBILITY.md section 3.1 for the full recipe):
#   - a conda env named `lifton` with LiftOn 1.0.9 installed, and
#   - a conda env named `smk` providing gffread (for the proteome step).
#   - results/liftoff/llama_liftoff.gff3 and results/miniprot/llama_miniprot.gff3
#     already generated by `snakemake`.
#
# Usage:
#   bash scripts/run_lifton.sh            # run from the workflow/ directory
#   THREADS=8 bash scripts/run_lifton.sh
# =====================================================================
set -euo pipefail

# --- Configuration ---------------------------------------------------
REF_ACC="${REF_ACC:-GCF_048564905.1}"          # Vicugna pacos, RefSeq
THREADS="${THREADS:-6}"
TARGET_FASTA="${TARGET_FASTA:-resources/target/genome.fasta}"
REF_FASTA="${REF_FASTA:-resources/reference/genome.fasta}"
REF_GFF_NCBI="${REF_GFF_NCBI:-resources/reference/annotation_ncbi.gff}"
LIFTOFF_GFF="${LIFTOFF_GFF:-results/liftoff/llama_liftoff.gff3}"
MINIPROT_GFF="${MINIPROT_GFF:-results/miniprot/llama_miniprot.gff3}"
OUT_GFF="${OUT_GFF:-results/lifton/llama_lifton_v2.gff3}"
OUT_FAA="${OUT_FAA:-results/proteomes/llama_lifton_v2.faa}"

# Optional conda activation (comment out if envs are already on PATH)
CONDA_SH="${CONDA_SH:-$(conda info --base 2>/dev/null)/etc/profile.d/conda.sh}"
if [ -f "$CONDA_SH" ]; then
    # shellcheck disable=SC1090
    source "$CONDA_SH"
fi

# --- Sanity checks ---------------------------------------------------
for f in "$TARGET_FASTA" "$REF_FASTA" "$LIFTOFF_GFF" "$MINIPROT_GFF"; do
    if [ ! -s "$f" ]; then
        echo "ERROR: required input missing or empty: $f" >&2
        echo "       Run the Snakemake pipeline first (Liftoff + miniprot branches)." >&2
        exit 1
    fi
done
mkdir -p "$(dirname "$OUT_GFF")" "$(dirname "$OUT_FAA")" "$(dirname "$REF_GFF_NCBI")"

# --- 1. Native NCBI reference GFF (section 3.2) ----------------------
# LiftOn requires the NATIVE NCBI GFF; an AGAT-processed annotation yields an
# invalid proteome (see REPRODUCIBILITY.md section 3.4).
#
# REFERENCE ASYMMETRY -- read before comparing branches. Because of this
# requirement, LiftOn starts from the FULL multi-isoform reference (86,028
# transcripts, 56,808 proteins), whereas Liftoff and miniprot are fed the
# AGAT-reduced one-transcript-per-gene annotation produced by the workflow when
# `keep_longest_isoform: true`. The three homology branches therefore do NOT
# share the same reference annotation. See the "Reference asymmetry" sections of
# README.md and REPRODUCIBILITY.md.
if [ ! -s "$REF_GFF_NCBI" ]; then
    echo ">> Downloading native NCBI GFF for ${REF_ACC} ..."
    ACC_NODOT="${REF_ACC%.*}"                    # GCF_048564905
    P1="${ACC_NODOT:4:3}"; P2="${ACC_NODOT:7:3}"; P3="${ACC_NODOT:10:3}"
    BASE="https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/${P1}/${P2}/${P3}"
    DIR=$(curl -s "${BASE}/" | grep -oP "${REF_ACC//./\\.}_[^/\"]+" | head -1)
    wget "${BASE}/${DIR}/${DIR}_genomic.gff.gz" -O "${REF_GFF_NCBI}.gz"
    gunzip -f "${REF_GFF_NCBI}.gz"
else
    echo ">> Reusing existing native NCBI GFF: ${REF_GFF_NCBI}"
fi

# --- 2. LiftOn (section 3.3) -----------------------------------------
# Default parameters: miniprot rescue, best-result selection with verification,
# gene-feature transfer. --legacy-merge is NOT used. Target genome precedes the
# reference on the command line.
echo ">> Running LiftOn (threads=${THREADS}) ..."
conda activate lifton 2>/dev/null || echo "   (could not 'conda activate lifton'; assuming lifton is on PATH)"
lifton \
    -g "$REF_GFF_NCBI" \
    -ad RefSeq \
    -L "$LIFTOFF_GFF" \
    -M "$MINIPROT_GFF" \
    -o "$OUT_GFF" \
    -t "$THREADS" \
    "$TARGET_FASTA" \
    "$REF_FASTA"
test -s "$OUT_GFF"

# --- 3. Proteome extraction (section 5) ------------------------------
echo ">> Extracting proteome with gffread ..."
conda activate smk 2>/dev/null || echo "   (could not 'conda activate smk'; assuming gffread is on PATH)"
gffread -y "$OUT_FAA" -g "$TARGET_FASTA" "$OUT_GFF"
test -s "$OUT_FAA"

echo ">> Done."
echo "   Annotation: $OUT_GFF"
echo "   Proteome  : $OUT_FAA"
echo "   Next: run BUSCO on $OUT_FAA (see REPRODUCIBILITY.md section 5)."
